- name: Destroy platform infra + cluster
  hosts: localhost
  gather_facts: no

  vars_files:
    - ./vars/cloud-providers-data.yaml

  vars:
    target_cloud: "{{ cloud | default('eks') }}"

  tasks:
    - include_tasks: tasks/validate.yaml
      tags: [always]
    - include_tasks: tasks/checkout_cloud_engineering.yaml
      tags: [always]
    - include_tasks: tasks/infra_destroy.yaml
      tags: [infra_destroy]
    - include_tasks: tasks/cluster_destroy.yaml
      tags: [cluster_destroy]