- name: Ensure workdir exists
  file:
    path: "{{ workdir }}"
    state: directory

- name: Clone or update cloud-engineering repo
  git:
    repo: "{{ cloud_engineering_repo }}"
    dest: "{{ workdir }}/cloud-engineering"
    version: master
    force: yes