- name: Ensure workdir exists
  tags: [always]
  ansible.builtin.file:
    path: "{{ repos.workdir }}"
    state: directory
    mode: "0755"

- name: Clone cloud-engineering repo
  tags: [always]
  ansible.builtin.git:
    repo: "{{ repos.cloud_engineering_repo }}"
    dest: "{{ repos.workdir }}/cloud-engineering"
    version: master
    force: yes