- name: Terraform init {{ cloud }} config 
  tags: [cluster_config]
  ansible.builtin.command:
    cmd: terraform init -upgrade
    chdir: "{{ repos.workdir }}/cloud-engineering/{{ clouds[cloud].config_tf_subdir }}"
  environment: "{{ clouds[cloud].env | default({}) }}"

- name: Terraform apply {{ cloud }} config
  tags: [cluster_config]
  ansible.builtin.command:
    cmd: terraform apply -auto-approve -var="cluster_name={{ cluster_name }}"
    chdir: "{{ repos.workdir }}/cloud-engineering/{{ clouds[cloud].config_tf_subdir }}"
  environment: "{{ clouds[cloud].env | default({}) }}"