- name: Delete Argo ApplicationSets
  tags: [infra_destroy]
  ansible.builtin.command:
    cmd: kubectl -n argocd-infra delete appsets --all
  ignore_errors: true

- name: Delete Argo Applications
  tags: [infra_destroy]
  ansible.builtin.command:
    cmd: kubectl -n argocd-infra delete applications --all
  ignore_errors: true

- name: Uninstall ArgoCD
  tags: [infra_destroy]
  ansible.builtin.command:
    cmd: helm -n argocd-infra uninstall argocd
  ignore_errors: true

- name: Force-delete platform namespaces
  tags: [infra_destroy]
  ansible.builtin.command:
    cmd: kubectl delete namespace observability-stack ingress-nginx ingress-infra ingress-internal ingress-external argocd-infra --grace-period=0 --force
  ignore_errors: true