# tasks/infra_deprovision.yaml

- name: Helm uninstall platform components (argocd, ingresscontrollers and observability stack).
  tags: [infra]
  command: >
    helm uninstall {{ item.release }}
    {{ infra_gitops_dir }}/{{ item.name }}
  loop:
    - { name: ingresscontroller,       release: ingress-nginx }
    - { name: observability,           release: observability }
  environment: "{{ cloud_env }}"