- name: Destroy platform infra (Helm uninstall)
  vars:
    components:
      - { name: observability, release: observability }
      - { name: ingresscontroller,       release: ingress-nginx }
      - { name: argocd-bootstrap,        release: argocd }

- name: Helm uninstall platform components
  command: helm uninstall {{ item.release }}
  loop: "{{ components }}"
  failed_when: false